services:
  api_gateway:
    image: fmsa-api_gateway:latest
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    environment:
      - SECRET_KEY=1234567890abcdefghijklmnopqrstuvwxyz
      - TOKEN_EXPIRED_MINUTES=600
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - REDIS_PASSWORD=redis
    depends_on:
      - api_gateway_access_token_storage
      - keycloak_adapter
    volumes:
      - ./api_gateway/:/app/

  api_gateway_access_token_storage:
    image: bitnami/redis:latest
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=redis
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 300mb
    volumes:
      - redis_api_gateway_access_token_storage:/bitnami/redis/data
    restart: always

  keycloak_adapter:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_adapter_postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    restart: always
    depends_on:
      - keycloak_adapter_postgres
    command:
      - start

  keycloak_adapter_postgres:
    image: postgres:14.10-alpine
    volumes:
      - keycloak_adapter_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    restart: always

  data_analysis_service:
    image: fmsa-data_analysis_service:latest
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./data_analysis_service/:/app/
    environment:
      - DATABASE_HOST=analysis_db
      - DATABASE_USER=default
      - DATABASE_PASSWORD=analysis_data
    depends_on:
      - analysis_db
    restart: always

  analysis_db:
    image: bitnami/clickhouse:24
    volumes:
      - clickhouse_analysis_data:/bitnami/clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - CLICKHOUSE_ADMIN_USER=default
      - CLICKHOUSE_ADMIN_PASSWORD=analysis_data
    restart: always

  ioht_data_collector:
    image: fmsa-ioht_data_collector:latest
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./ioht_data_collector/:/app/
    environment:
      - DATABASE_HOST=ioht_db
      - DATABASE_USER=default
      - DATABASE_PASSWORD=ioht_data
    depends_on:
      - ioht_db
    restart: always

  ioht_db:
    image: bitnami/clickhouse:24
    volumes:
      - clickhouse_ioht_data:/bitnami/clickhouse
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - CLICKHOUSE_ADMIN_USER=default
      - CLICKHOUSE_ADMIN_PASSWORD=ioht_data
    restart: always

  fhir_generator:
    image: fmsa-fhir_generator:latest
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./fhir_generator/:/app/
    restart: always

  fhir_converter:
    image: fmsa-fhir_converter
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./fhir_converter/:/app/
    restart: always

  fhir_ig_manager:
    image: fmsa-fhir_ig_manager:latest
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./fhir_ig_manager/:/app/
    environment:
      - FHIR_IG_MANAGER_DB_USER=fhir_ig_manager_username
      - FHIR_IG_MANAGER_DB_PASSWORD=fhir_ig_manager_password
      - FHIR_IG_MANAGER_DB=fhir_ig_manager_db_dev
    depends_on:
      - fhir_ig_manager_db
    restart: always

  fhir_ig_manager_db:
    image: mongo:7.0.16-jammy
    volumes:
      - fhir_ig_manager_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fhir_ig_manager_username
      - MONGO_INITDB_ROOT_PASSWORD=fhir_ig_manager_password
      - MONGO_INITDB_DATABASE=fhir_ig_manager_db_dev
    restart: always

  fhir_profile_manager:
    image: fmsa-fhir_profile_manager
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./fhir_profile_manager/:/app/
    environment:
      - FHIR_PROFILE_MANAGER_DB_USER=fhir_profile_manager_username
      - FHIR_PROFILE_MANAGER_DB_PASSWORD=fhir_profile_manager_password
      - FHIR_PROFILE_MANAGER_DB=fhir_profile_manager_db_dev
    depends_on:
      - fhir_profile_manager_db
    restart: always

  fhir_profile_manager_db:
    image: mongo:7.0.16-jammy
    volumes:
      - fhir_profile_manager_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fhir_profile_manager_username
      - MONGO_INITDB_ROOT_PASSWORD=fhir_profile_manager_password
      - MONGO_INITDB_DATABASE=fhir_profile_manager_db_dev
    restart: always

  fhir_data_manager:
    image: fmsa-fhir_data_manager:latest
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./fhir_data_manager/app/tests:/app/app/tests
      - ./fhir_data_manager/app/modules:/app/app/modules
      - ./fhir_data_manager/app/routers:/app/app/routers
      - ./fhir_data_manager/app/item_models:/app/app/item_models
      - ./fhir_data_manager/app/main.py:/app/app/main.py
      - ./fhir_data_manager/app/__init__.py:/app/app/__init__.py
    environment:
      - FHIR_DATA_MANAGER_DB_USER=fhir_data_manager_username
      - FHIR_DATA_MANAGER_DB_PASSWORD=fhir_data_manager_password
      - FHIR_DATA_MANAGER_DB=fhir_data_manager_db_dev
    depends_on:
      - fhir-server-adapter
      - fhir_server_adapter_postgres
      - fhir_data_manager_db
    restart: always

  fhir_data_manager_db:
    image: mongo:7.0.16-jammy
    volumes:
      - fhir_data_manager_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fhir_data_manager_username
      - MONGO_INITDB_ROOT_PASSWORD=fhir_data_manager_password
      - MONGO_INITDB_DATABASE=fhir_data_manager_db_dev
    restart: always

  fhir-server-adapter:
    image: "hapiproject/hapi:v7.6.0"
    volumes:
      - ./fhir_server_adapter/hapi.application.yml:/app/config/application.yaml:ro
    depends_on:
      - fhir_server_adapter_postgres

  fhir_server_adapter_postgres:
    image: postgres:14.10-alpine
    volumes:
      - fhir_server_adapter_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fhir_data_manager_username
      - POSTGRES_PASSWORD=$fhir_data_manager_password
      - POSTGRES_DB=fhir_data_manager_db_dev
    restart: always

  terminology_manager:
    image: fmsa-terminology_manager:latest
    command: uvicorn app.main:app --host 0.0.0.0 --workers 4 --port 8000
    volumes:
      - ./terminology_manager/:/app/
    environment:
      - TERMINOLOGY_MANAGER_DB_USER=terminology_manager_username
      - TERMINOLOGY_MANAGER_DB_PASSWORD=terminology_manager_password
      - TERMINOLOGY_MANAGER_DB=terminology_manager_db_dev
    depends_on:
      - terminology_manager_db
    restart: always

  terminology_manager_db:
    image: mongo:7.0.16-jammy
    volumes:
      - terminology_manager_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=terminology_manager_username
      - MONGO_INITDB_ROOT_PASSWORD=terminology_manager_password
      - MONGO_INITDB_DATABASE=terminology_manager_db_dev
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 8081:8081
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_gateway
      - data_analysis_service
      - ioht_data_collector
      - fhir_generator
      - fhir_converter
      - fhir_ig_manager
      - fhir_profile_manager
      - fhir_data_manager
      - terminology_manager
    restart: always

volumes:
  redis_api_gateway_access_token_storage:
  clickhouse_analysis_data:
  clickhouse_ioht_data:
  keycloak_adapter_postgres_data:
  fhir_server_adapter_postgres_data:
  fhir_data_manager_data:
  fhir_ig_manager_data:
  fhir_profile_manager_data:
  terminology_manager_data:
