spring:
  datasource:
    url: 'jdbc:postgresql://fhir_server_adapter_postgres:5432/fhir_data_manager_db_dev'
    username: fhir_data_manager_username
    password: fhir_data_manager_password
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: true
