spring:
  datasource:
    url: 'jdbc:postgresql://fhir_server_adapter_postgresql:5432/fhir'
    username: postgres
    password: openstack
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
