name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: cp docker-compose-http.yml docker-compose.yml && cp .env.ci .env
      - run: docker compose up -d --build && sleep 5
      - run: |
          ./run_unit_tests.sh fhir_converter
          ./run_unit_tests.sh fhir_data_manager

          ./run_unit_tests.sh fhir_generator ./app/tests/test_iclaim_imri_resource.py
          ./run_unit_tests.sh fhir_generator ./app/tests/test_pa_sc1.py

          ./run_unit_tests.sh fhir_ig_manager
          ./run_unit_tests.sh fhir_profile_manager
          ./run_unit_tests.sh ioht_data_collector
          ./run_unit_tests.sh terminology_manager
          ./run_unit_tests.sh data_analysis_service
