name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: cp docker-compose-http.yml docker-compose.yml && cp .env.ci .env
      - run: |
          docker compose build --no-cache && docker compose up -d && sleep 30
          ./run_unit_tests.sh fhir_data_manager ./app/tests/test_upload_resource.py -s
