name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: cp docker-compose-http.yml docker-compose.yml
      - run: docker compose up -d --build
      - run: ./run_unit_tests.sh fhir_converter
